#!/usr/bin/env python3
"""
Compiler-warning baseline and triage for MagisV2.

Why this exists
---------------
A clean build of PRIMUS_X2_v1 emits ~2700 warnings, ~1700 of them from the
vendored `lib/` tree that we do not own. A warning introduced by your change is
invisible in that noise. This tool records a baseline of the warnings that are
already there and reports only what your change *added*.

The compiler is the analyser. The build already runs with -Wall -Wextra
-Wconversion -Wsign-conversion -Wshadow -Wdouble-promotion over 100% of the
tree, C and C++ alike. `make cppcheck` covers only the 49 `.c` files (a third of
the tree, none of `flight/`), needs a tool that is not installed here, and
hardcodes Linux include paths -- so it is not the analysis path. This is.

Usage
-----
    make TARGET=PRIMUS_X2_v1 clean && make TARGET=PRIMUS_X2_v1 2>&1 | tee build.log

    python3 tools/warnings.py baseline build.log      # record current state
    python3 tools/warnings.py check    build.log      # diff against baseline
    python3 tools/warnings.py summary  build.log      # counts by flag and file

`check` exits 1 if the change added any warning under `src/`, 0 otherwise.
Warnings from `lib/` are counted but never fail the check -- that tree is
upstream and we do not reformat or fix it.

A warning is fingerprinted as (file, flag, message) with a count, deliberately
ignoring line and column numbers: inserting a line above an existing warning
must not look like a new finding, while a genuinely new instance of the same
warning in the same file still raises the count and is reported.
"""

import argparse
import collections
import json
import os
import re
import sys

BASELINE_DEFAULT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "warnings-baseline.json")

# "./src/main/flight/pid.cpp:123:45: warning: conversion from 'int' ... [-Wconversion]"
# The column group is optional; some GCC diagnostics and all linker warnings omit it.
WARN_RE = re.compile(
    r"^(?P<file>[^\s:][^:]*?):(?P<line>\d+):(?:(?P<col>\d+):)?\s+warning:\s+(?P<msg>.*?)\s*$"
)
FLAG_RE = re.compile(r"\[(-W[a-z0-9+-]+)\]\s*$")


def normalise_path(path):
    """Repo-relative, forward slashes, no leading './'."""
    path = path.replace("\\", "/")
    while path.startswith("./"):
        path = path[2:]
    # Absolute toolchain paths (libc, gcc internals) collapse to a single bucket.
    if ":" in path.split("/")[0] and len(path.split("/")[0]) == 2:
        return "<toolchain>"
    idx = path.find("src/main/")
    if idx > 0:
        return path[idx:]
    idx = path.find("lib/main/")
    if idx > 0:
        return path[idx:]
    return path


def scope_of(path):
    if path.startswith("src/"):
        return "src"
    if path.startswith("lib/"):
        return "lib"
    return "other"


def parse(log_path):
    """Return {fingerprint_key: count} where key is 'file\x1fflag\x1fmessage'."""
    counts = collections.Counter()
    try:
        with open(log_path, "r", encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()
    except OSError as exc:
        sys.exit("cannot read build log %s: %s" % (log_path, exc))

    for raw in lines:
        # Strip ANSI colour the Makefile emits for progress lines.
        raw = re.sub(r"\x1b\[[0-9;]*m", "", raw.rstrip("\n"))
        m = WARN_RE.match(raw)
        if not m:
            continue
        msg = m.group("msg")
        flag_m = FLAG_RE.search(msg)
        if flag_m:
            flag = flag_m.group(1)
            msg = msg[: flag_m.start()].rstrip()
        else:
            flag = "(no-flag)"
        path = normalise_path(m.group("file"))
        counts["\x1f".join((path, flag, msg))] += 1
    return counts


def unpack(key):
    return key.split("\x1f", 2)


def load_baseline(path):
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    return collections.Counter(data.get("warnings", {}))


def cmd_baseline(args):
    counts = parse(args.log)
    payload = {
        "_comment": "Generated by tools/warnings.py. Regenerate only when the added "
                    "warnings are deliberate and reviewed.",
        "target": args.target,
        "total": sum(counts.values()),
        "warnings": dict(counts),
    }
    with open(args.baseline, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True)
        fh.write("\n")
    by_scope = collections.Counter()
    for key, n in counts.items():
        by_scope[scope_of(unpack(key)[0])] += n
    print("baseline written: %s" % args.baseline)
    print("  total %d  (src %d, lib %d, other %d)"
          % (sum(counts.values()), by_scope["src"], by_scope["lib"], by_scope["other"]))
    return 0


def cmd_check(args):
    base = load_baseline(args.baseline)
    if base is None:
        sys.exit("no baseline at %s -- run: python3 tools/warnings.py baseline <log>"
                 % args.baseline)
    now = parse(args.log)

    added, removed = [], []
    for key, n in now.items():
        delta = n - base.get(key, 0)
        if delta > 0:
            added.append((key, delta))
    for key, n in base.items():
        delta = n - now.get(key, 0)
        if delta > 0:
            removed.append((key, delta))

    src_added = [(k, d) for k, d in added if scope_of(unpack(k)[0]) == "src"]
    other_added = [(k, d) for k, d in added if scope_of(unpack(k)[0]) != "src"]

    if src_added:
        print("NEW WARNINGS IN src/  (%d)" % sum(d for _, d in src_added))
        for key, delta in sorted(src_added, key=lambda kv: unpack(kv[0])[0]):
            path, flag, msg = unpack(key)
            print("  %s  %s  x%d" % (path, flag, delta))
            print("      %s" % msg)
    else:
        print("no new warnings in src/")

    if other_added and args.verbose:
        print("\nnew warnings outside src/ (not a failure) (%d)"
              % sum(d for _, d in other_added))
        for key, delta in sorted(other_added, key=lambda kv: unpack(kv[0])[0])[:20]:
            path, flag, _ = unpack(key)
            print("  %s  %s  x%d" % (path, flag, delta))

    src_removed = [(k, d) for k, d in removed if scope_of(unpack(k)[0]) == "src"]
    if src_removed:
        print("\nfixed in src/ (%d) -- refresh the baseline once these are committed"
              % sum(d for _, d in src_removed))
        for key, delta in sorted(src_removed, key=lambda kv: unpack(kv[0])[0])[:20]:
            path, flag, _ = unpack(key)
            print("  %s  %s  x%d" % (path, flag, delta))

    return 1 if src_added else 0


def cmd_summary(args):
    counts = parse(args.log)
    by_flag = collections.Counter()
    by_file = collections.Counter()
    by_scope = collections.Counter()
    for key, n in counts.items():
        path, flag, _ = unpack(key)
        by_flag[flag] += n
        by_file[path] += n
        by_scope[scope_of(path)] += n

    print("total %d  (src %d, lib %d, other %d)\n"
          % (sum(counts.values()), by_scope["src"], by_scope["lib"], by_scope["other"]))
    print("by flag:")
    for flag, n in by_flag.most_common(args.top):
        print("  %6d  %s" % (n, flag))
    print("\nby file (src/ only):")
    src_files = [(f, n) for f, n in by_file.most_common() if scope_of(f) == "src"]
    for path, n in src_files[: args.top]:
        print("  %6d  %s" % (n, path))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--baseline", default=BASELINE_DEFAULT,
                    help="baseline JSON (default: tools/warnings-baseline.json)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("baseline", help="record the warnings in a build log as the baseline")
    p.add_argument("log")
    p.add_argument("--target", default="PRIMUS_X2_v1")
    p.set_defaults(func=cmd_baseline)

    p = sub.add_parser("check", help="report warnings a build log added over the baseline")
    p.add_argument("log")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="also list new warnings outside src/")
    p.set_defaults(func=cmd_check)

    p = sub.add_parser("summary", help="counts by flag and file")
    p.add_argument("log")
    p.add_argument("--top", type=int, default=15)
    p.set_defaults(func=cmd_summary)

    args = ap.parse_args()
    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
